[phases.setup]
nixPkgs = ["...","python310", "postgresql", "gcc"]
nixLibs = ["...", "gcc-unwrapped", "zlib", "stdenv.cc.cc.lib"]


[phases.install]
cacheDirectories = ["...", "/root/.cache/pip"]
paths = ["...", "/opt/venv/bin"]
cmds = [
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate && pip install poetry==1.8.3 && poetry install --without dev --no-interaction --no-ansi",
    "..."
]
dependsOn = ["setup"]

[phases.management]
cmds = ["python manage.py collectstatic --no-input", "python manage.py migrate"]
dependsOn = ["install"]
