# Generated by Django 5.1.1 on 2024-09-17 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='role',
            field=models.CharField(choices=[('system', 'system'), ('user', 'user'), ('assistant', 'assistant')], max_length=50),
        ),
    ]
