# Generated by Django 5.1.1 on 2024-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio_link',
            field=models.URLField(null=True),
        ),
    ]
