# Generated by Django 5.1.1 on 2024-09-18 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_message_audio_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_link',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
