# Generated by Django 5.1.1 on 2024-09-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_message_audio_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('created_at',)},
        ),
        migrations.AddField(
            model_name='message',
            name='english_translation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
