# Generated by Django 5.1.1 on 2024-09-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_message_options_message_english_translation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='english_translation',
            field=models.TextField(blank=True, default=''),
        ),
    ]
